### ISSUE TITLE
where is the download link i want to try this? :)

### ISSUE THREAD

**Issue by viktorblack** [fzwoch/obs-teleport#10]
where is the download link i want to try this? :)

**Comment by fzwoch** [comment]
The code is still in flux and it does crash and deadlock on some platforms. So no official binaries yet. I'd like to cleanup the rough edges so that it is at least testable. What platform are you looking for, I may drop somethiung here then if i consider it worth trying.

**Comment by viktorblack** [comment]
hey thx for the fast response im using windows =)

**Comment by fzwoch** [comment]
[windows.zip](https://github.com/fzwoch/obs-teleport/files/7806213/windows.zip)
Here is a snapshot that may actually work. Give it a try.

**Comment by fzwoch** [comment]
First beta release is in the release section, so closing this one.
