### ISSUE TITLE
Feature request: Support alpha channel

### ISSUE THREAD

**Issue by loveolsson** [fzwoch/obs-teleport#100]
A lot of the use-cases for sending video between OBS-instances is to distribute graphic overlays in different ways, and more often than not this needs the alpha channel. I use NDI for this today, but I would love to be able to use Teleport.

While JPEG itself doesn't support alpha channel, it would be super useful to have the option to send the alpha as a separate monochrome JPEG stream. Basically an optional second image buffer at the end of the Teleport Packet for the alpha.

**Comment by fzwoch** [comment]
Unlikely that I will add this here, but have you looked at https://github.com/YorVeX/xObsBeam?

**Comment by loveolsson** [comment]
I have not, thank you for the suggestion.

**Comment by YorVeX** [comment]
@loveolsson You can see [here in the table](https://github.com/YorVeX/xObsBeam/wiki/Compression-help) which compression settings support an alpha channel. Note that all of those options have a higher bandwidth usage than Teleport/JPEG so it might need some tweaking to get it right for your network.

Your feature request to also do this for JPEG with a separate data stream would something I could consider doing for Beam, feel free to also open the same feature request there, though I won't make any promises about timelines.
