### ISSUE TITLE
windows-ubuntu, ubuntu dont find windows teleport obs

### ISSUE THREAD

**Issue by theduodecim** [fzwoch/obs-teleport#101]
.when i enable the windows teleport, the ubuntu machine dont find windows obs teleport
.windows machine finds ubuntu obs teleport
**checking ubuntu machine reacheable ip+port** : _Connection to 192.168.0.101 5555 port [tcp/*] succeeded!_

notes: 
to windows to windows works fine

**Comment by fzwoch** [comment]
Something is blocking the multicast for discovery. Probably Windows. Others seem to have noticed you need to set it to in a private network or so. Not sure, I don't use Windows.

**Comment by YorVeX** [comment]
yes, that's something worth trying, as described here: https://obsproject.com/forum/threads/teleport.152081/page-13#post-651620

also try the classic: disable windows firewall. if it then works, you know you need to figure out how to allow teleport through it.

3rd option would be that you have a 3rd party security suite like norton. many of them call themselves very generally something with "security" but don't make it clear that part of the suite is also a firewall. also try temporarily disabling those.

**Comment by fzwoch** [comment]
https://www.youtube.com/watch?v=uwymlsCGkQw
Something like that? Wished Microsoft would be more precise of the implications of these settings..
