### ISSUE TITLE
unable to remove plugin

### ISSUE THREAD

**Issue by FlockersDesign** [fzwoch/obs-teleport#102]
When removing all the Teleport files from OBS
for some reason when you then open obs again its all back 

and you get in to a uninstall loop and it will never be removed
the only way is a fresh obs install but i am not planning on doing that because my obs is way to advanced to set this all back up
that will take anges

![{82FCBF6D-AD8A-411D-BFCD-2BDE78E7521C}](https://github.com/user-attachments/assets/b99134cd-dab4-4669-b74d-9268a1985aa7)

**Comment by fzwoch** [comment]
Check https://obsproject.com/kb/plugins-guide about potential install locations which depent on the verion you have installed.

**Comment by FlockersDesign** [comment]
Yea i know that i mean thays the most basic logic out there
But clearly somthing is wrong with this plugin and some how forces itself
to stay installed

Uninstalling plugins is simple im not new to obs nor plugins use it for
years

So instead of giving a simple awnser everyone knows and closing you
proberly better of giving it a bit more of a tought

**Comment by fzwoch** [comment]
There is no logic to replicate itself in the plugin..

**Comment by FlockersDesign** [comment]
Well here you go seems you need a video to see the problem 
but wasnt supriced seeing your other comments
of nor profecional support

https://youtu.be/S7MePHy_Q9M?si=Qiz5xebSJ5zQnnie

**Comment by fzwoch** [comment]
You are deleting a `.json` config file for Teleport. Not the plugin. Check `C:\ProgramData\obs-studio\plugins` as the kb from my first reply suggests.

Please acknowledge that this plugin is a free software without any liability. There is no "professional" support. People are more than welcome to report `bugs` with the plugin but I cannot be a first level support, so I shot down things quickly.

**Comment by FlockersDesign** [comment]
If you look at the compleete video you see i went true all the folders
Plus its a PORTABLE INSTALL so no files are in the appdata folder
Thay is only if its installed in a non portable version
How do you not know that

Nvm
If you dont want to help or say something is wrong with the plugin so be it
but stop playing pingpong

**Comment by FlockersDesign** [comment]
Appdata = ProgramData

**Comment by fmjensen** [comment]
I cannot replicate the problem you report. And winder if anybody else can replicate your bug report. If not, then the problem probably is related to your OBS setup or Plugin removal process.
