### ISSUE TITLE
I change the install.sh on Linux version installer. for flatpak install, where i put it?

### ISSUE THREAD

**Issue by Vol1t** [fzwoch/obs-teleport#103]

**Comment by fzwoch** [comment]
Not sure I understand.

The install scripts are not part of this repository. It is a bunch of lose scripts on my disk.
Flatpak installs outside of the Flatphub ecosystem are not supported and may break any time.

I would recommend to create a Flathub repository with a build script to make this available for Flatpak installs.

**Comment by fzwoch** [comment]
Closing due to no feedback
