### ISSUE TITLE
No longer able to open OBS after install

### ISSUE THREAD

**Issue by redrussak** [fzwoch/obs-teleport#106]
I installed the latest version and as a result, no longer able to open OBS (latest version) on Macbook M1 Sonoma OS. 

1. Installed Plugin
2. Clicked mac folder > installer
3. Approved developer in Privacy
4. OBS won't open - keeps timing out
5. Dragged plugin files to trash
6. Deleted OBS from computer
7. Restarted mac
8. Clicked OBS
9. Won't open - icon keeps jumping up from dock and stalling out without ever opening the application

I need this resolved ASAP and hoping you can aid in finding a solution. Thank you for your help in advance.

**Comment by fzwoch** [comment]
This seems to be #43

**Comment by fzwoch** [comment]
Check https://obsproject.com/kb/plugins-guide for plugin install locations for removel.

**Comment by redrussak** [comment]
Problem solved. Thank you very much!

> ~/Library/Application Support/obs-studio/plugins
> 
> Within this folder, there should be separate bundles for each plugin ending with .plugin. If you view these in Finder, they look like white plastic toy bricks.
