### ISSUE TITLE
for the life of me, i cant get this to uninstall

### ISSUE THREAD

**Issue by kevmuller** [fzwoch/obs-teleport#108]
I've clean installed obs numerous times, made sure the obs folder is gone, flushed the appdata folder, and every time i reinstall its there, please help

**Comment by fzwoch** [comment]
It should be `C:\ProgramData\obs-studio\plugins`

See https://obsproject.com/kb/plugins-guide

**Comment by kevmuller** [comment]
Thank you! Sorry i was struggling to find this

________________________________
