### ISSUE TITLE
Filter output not working

### ISSUE THREAD

**Issue by devnix** [fzwoch/obs-teleport#110]
Hi! I'm on an Ubuntu 22.04 machine with the .deb installation of OBS trying to stream to a Windows machine.

As I'm trying to send both desktop and camera, I'm trying the filter output. I can set up a name: 
![image](https://github.com/user-attachments/assets/037f56a6-ffb9-48d4-bda4-aa505b9efcf5)

and it will appear listed as a source, but will not get any output from there:
![image](https://github.com/user-attachments/assets/2683f532-1fa9-4464-b4e5-b627bbd34c9d)

I confirmed first that it works with the output mode, so I'm not sure if I'm missing something or if this can be a bug

**Comment by devnix** [comment]
A bit more of info: it seems like when the Windows machine selects the filter teleport source, it appears in the Ubuntu machine's log:
![image](https://github.com/user-attachments/assets/869d6c0f-a38c-44f9-8762-994287b43fad)

**Comment by fzwoch** [comment]
I tried with a media source and it seems to work fine within in the same OBS at least.

Perhaps you camera does use a specific color space that does not work?

**Comment by fzwoch** [comment]
Oh.. I think you need to select `Teleport (Video)` as a filter. Else the receiver will expect audio as well, which probably is not going to happen on a video only feed.

**Comment by devnix** [comment]
Oh, it seems like it works. I was interested on the audio too, is that doable?

Also I'm trying to add this too on a screenshare source too, otherwise I'm forced to open two instances of OBS

**Comment by fzwoch** [comment]
The cam source probably does not deliver audio. Most likely you need add another source for that. But then you cannot sync them properly. That is just a limitation of how it can work within OBS in these cases.

Screenshare source will only work if it is an asynchronous source. Iirc it is not.

**Comment by devnix** [comment]
>Perhaps you can add it as a filter to scenes? I cannot remember.

I can't (or can't find the way to). As I would understand, a scene is a compound of synchronoys and asynchronous sources, and that would limit the filters to synchronous (based on pure guess)

**Comment by fzwoch** [comment]
Yeah. most likely. I cannot remember.

You'll just have to have two sources with a Teleport filter each and cross fingers they are kind of in sync on the receiver side. Eventually requires some latency compensation. This is as far as sync goes from an OBS point of view. Therefore a single source with audio and video is preferred.

I have no idea for the screen share though.

**Comment by fzwoch** [comment]
Closing this, as it works as it is currently designed.
