### ISSUE TITLE
No feed coming through

### ISSUE THREAD

**Issue by lindenkron** [fzwoch/obs-teleport#12]
Attempting to set up teleport on our other broadcasters PC, we've run into the issue of nothing appearing when attempting to set it up.

I've already sucessfully managed to set up and test things on my own local setup.

This is what it looks like.
https://i.imgur.com/Se83XjB.png

Here are the two OBS logs.

**Sending PC**
https://obsproject.com/logs/2hlOUPOxSQNw96ZT

**Receiving PC**
https://obsproject.com/logs/zzRAncqzpIrrJz4w

**Comment by fzwoch** [comment]
Can the PCs ping each other? Firewall? Can you spot some encoding load on the sender PC when trying to receive the stream?

**Comment by fzwoch** [comment]
```
18:00:37.774: 	Windows Firewall: enabled (FW)
```
Firewall seems to be on on the sending PC.

**Comment by 4p3rtur3** [comment]
Same here, no Picture, no GPU or CPU load differencies but a slight network traffic(increase) of ~3,3Mbit/s.

**Comment by fzwoch** [comment]
Yeah, I444 definitely is not supported atm, probably never will.

**Comment by fzwoch** [comment]
Closing this one as I assume the original issue is due to enabled Windows firewall.
