### ISSUE TITLE
Scene Selection - Game Capture under source?

### ISSUE THREAD

**Issue by BeholdLIVE** [fzwoch/obs-teleport#13]
Hello all,

Teleport is outstanding for transmitting saved media content. WOW, I've tested it now and great job Fzwoch!!

I do have one question, how does one transfer over something such as a **DESKTOP** or a **GAME CAPTURE** source from a GAMING PC to a STREAM PC? Am I missing this? I apologize if this is incredibly easy to do. I've tried repeating the instructions a few times.

I do not have filter options in teleport in order to do this - It does work for locally saved media content though.  

Thank you for your help in advance, I hope you make it real big with this!

**Comment by 4p3rtur3** [comment]
You just need to enable the Plugin on you Transmitting OBS via **Tools(T)** --> **Teleport** --> _check_ **"Teleport Enabled"**, thats it. 
![Tools](https://user-images.githubusercontent.com/33102632/152103573-14317bb6-ab44-499c-b10c-fb55cb6c730c.png)
![Teleport](https://user-images.githubusercontent.com/33102632/152103528-16b5071c-e757-4202-81d7-29cc9eaa5d76.png)
Now everything OBS captures will be "teleported"/transmitted to where its requested.
### **Make sure you are NOT using I444 as Color Format!!!**

Then you just have to create a "Teleport" Source in your recieving OBS, "Refresh List" and select your desired device.
![Source](https://user-images.githubusercontent.com/33102632/152104527-122824dd-1775-47b4-8c40-7b82102d0da4.png)

**Comment by fzwoch** [comment]
4p3rtur3 summed it up pretty well.

If you wanted to use the filter feature for a source/scene, it only works if there is the "Audio/Video filter" column. If there is only "Effect filter" column it will not work and you will have to use the "output" module as described above.

**Comment by fzwoch** [comment]
Closing for now. If this is about effect filters - it is not yet implemented.
