### ISSUE TITLE
It is recommended to add windows installation package for easy installation.

### ISSUE THREAD

**Issue by iesvme** [fzwoch/obs-teleport#17]
It is recommended to add windows installation package for easy installation.

**Comment by iesvme** [comment]
such as "Inno Setup Compiler"

**Comment by fzwoch** [comment]
There is a small installer since 0.2.4. Hope it works :crossed_fingers:

**Comment by iesvme** [comment]
That's very good! Very amazing plugin!
But I don't understand what the peerdiscovery.diff is. Does it need to be
installed?

Florian Zwoch ***@***.***> 于2022年2月20日周日 19:33写道：

**Comment by fzwoch** [comment]
It is more more fort GPL compliance, the build uses that patch from an upstream dependency which is not merged.

**Comment by iesvme** [comment]
Thanks for your answer. But I still do not understand. Sorry :)

**Comment by fzwoch** [comment]
Just ignore it. It is only there for "legal" reasons.
