### ISSUE TITLE
filter unavailable for Syphon

### ISSUE THREAD

**Issue by thehumangerm** [fzwoch/obs-teleport#18]
Filter unavailable in Syphon client scene in macOS version. This is needed for use with Serato or game streaming. If this is not an available feature please update readme accordingly. Thanks.

**Comment by fzwoch** [comment]
If that requires an "effect filter" it is not "just an update".

Also I'm not convinced if that's available, audio will pass there as well, causing all sorts of sync issues.

**Comment by fzwoch** [comment]
Added a note about effect filters in 4bd9bb050fae1435dc3bc7dd9ca4a68e378718bb.
