### ISSUE TITLE
Great OBS solution - how to build it on Raspberry PI ?

### ISSUE THREAD

**Issue by FilipStadler** [fzwoch/obs-teleport#19]
I have succesful installed the binary on windows10 and Ubuntu 20.10,20.04 and it works well.

It would be usefull to build it on my Raspberry Pi4 with Bullseye Debian to see how it would perform.
I just do know so much about go - what is needed to build binary on rpi4.

Anyway really usefull alternative to NDI  - Great job.

**Comment by fzwoch** [comment]
Regular `go build` steps apply. You will need to link to `libobs` and `libjpeg`.

I will not maintain any detailed build instructions in this project itself. For an example you can check here:
https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=obs-teleport

**Comment by fzwoch** [comment]
P.s. I believe the release zip includes a linux arm64 build. I guess that may work if you have installed a 64 bit Raspberry PI OS.
