### ISSUE TITLE
0.24  could add the uninstaller in the control panel

### ISSUE THREAD

**Issue by iesvme** [fzwoch/obs-teleport#20]
0.2.4 is very good, but it could add the uninstaller in the control panel of the system to uninstall it. And it could be overwritten the old version in the next upgrade of the plugin as well.

**Comment by fzwoch** [comment]
Maybe i will add an uninstaller for next version, does anyone ever uses that? Re-running the install should overwrite the current plugin, is it not?

**Comment by iesvme** [comment]
Sorry, yes, it is. Re-running will overwrite it. 
Adding uninstall is just convenient to check the version number or debug. I think it is impossible that anyone who will uninstall such this excellent plugin!

**Comment by fzwoch** [comment]
I did take a look at it. It would require fiddling with the Windows registry, create an extra folder for this plugin and store an uninstaller application in it.

I'd rather not have this kind of complexity for this simple thing. So I keep it is at is at the moment where it just checks the OBS install dir to automatically fill ion the install path and that's it.

**Comment by iesvme** [comment]
It's okay to keep it simple. Then there is no need to add an uninstaller. Just focus on improving the plugin's functionality.
