### ISSUE TITLE
The colors of camera are different

### ISSUE THREAD

**Issue by iesvme** [fzwoch/obs-teleport#21]
Nv12

![mmexport1645422865304](https://user-images.githubusercontent.com/16969250/154897286-30934006-9b5f-4dcb-bec6-95c141ae9a6b.png)

**Comment by fzwoch** [comment]
Was it a false alarm? I certainly can imagine that there may be a problem with full range and partial range sources as the plugin currently does not distinguish between these two different possibilities.

**Comment by iesvme** [comment]
I'm, so sorry. I tweaked the filter color on both obs so it looked different. Now solved.
