### ISSUE TITLE
[Feature Request] Protocol Documentation

### ISSUE THREAD

**Issue by enzanki-ars** [fzwoch/obs-teleport#22]
Based on a quick look through of the code, it looks like the protocol is on the simpler side, and if so, I think it would be wonderful to have documentation on the protocol in order to potentially create some unique possibilities that were much harder with NDI.

**Comment by fzwoch** [comment]
I'd rather not maintain an extra documentation for it. (lazy)

But also as it would also kinda imply that the protocol would be stable - which it isn't. Also it is not specially thought out. It is just there to make things work and may change anytime.

But as you figured, it is kinda simple, so current code is it's documentation atm.

**Comment by fzwoch** [comment]
Closing as it will probably never happen.
