### ISSUE TITLE
[Feature Request] Option to disable stream while not visible

### ISSUE THREAD

**Issue by no-connections** [fzwoch/obs-teleport#23]
Currently the stream is active until disabled even when not visible.
It would be great if there was an option box (per source) to have it connect and disconnect when not visible since there is a lot of traffic at higher quality settings.

**Comment by fzwoch** [comment]
This is currenlty not present because it is related to #15. That will cause increasing audio delay when switching it on and off.

**Comment by fzwoch** [comment]
Closing. Actually the next version will have even less special handling cases. It is just too fragile and inconsistent for different use cases. It will be running when set up and that's it.
