### ISSUE TITLE
[Feature Request] Ability to stream to multiple receivers

### ISSUE THREAD

**Issue by rezonant** [fzwoch/obs-teleport#24]
It seems right now that if two receivers attempt to pull one Teleport stream, neither receiver can pull the video. As soon as I stop pulling from one of the receivers, the other receiver starts working.

Teleport would probably be perfect for us if we could have multiple receivers. That is one thing unique to NDI right now that keeps us on it (as opposed to SRT or RIST which are single-destination), but NDI is rather prone to A/V desync when under CPU load.

**Comment by fzwoch** [comment]
Fair enough. For simplicity I went with a single consumer. I will think about it by chance, but no ETA.

**Comment by fzwoch** [comment]
Should be possible starting with [0.4.0](https://github.com/fzwoch/obs-teleport/releases/tag/0.4.0)
