### ISSUE TITLE
Quality setting and resource usage

### ISSUE THREAD

**Issue by warcode** [fzwoch/obs-teleport#30]
Teleporting a 4k game source at 90% quality works fantastic.

Increasing the quality between 90% and 100% increases both network usage AND resource usage, eventually causing rendering lag in OBS. It seems counter-intuitive from a raw vs encoding tradeoff standpoint. Is this just how things work?

**Comment by fzwoch** [comment]
Yes, this is how it works basically. You can read about quality info directly from the jpeg library:

https://github.com/libjpeg-turbo/libjpeg-turbo/blob/main/usage.txt

**Comment by warcode** [comment]
Then it works correctly. Thank you!
