### ISSUE TITLE
[Feature Request] Allow teleport to listen over vpn connections

### ISSUE THREAD

**Issue by nnichols133** [fzwoch/obs-teleport#32]
I admit, I'm not sure if this is a real issue or if I am doing something wrong. I apologize if I am just doing something wrong. I would like to set up a tunnel to allow teleport to be accessed on a PC in another area, on another network, over the internet. I am not sure if I am doing something wrong, or if teleport has a restriction to local network only and is just not listening on the tunnel network.  

The use case for me is that I would like to have my buddy have access to my screen/game/webcam from my computer, on his OBS to his stream. Our specific use case is for podcasting and to allow his viewers to see my gameplay in his stream along side his gameplay. Think split screen gaming.

**Comment by fzwoch** [comment]
The discovery protocol uses multicast. So if the VPN forwards that it should be fine. It may be that they don't as it may not be trivial.

But also if it did, the bandwidth this plugin is using is not suited to be send over the internet. Depending on what is being send it easily requires 100-200 mbps. That's is why streaming tools exist in the first place, this plugin will not replace them.

**Comment by nnichols133** [comment]
Thanks for the response! i definitely wasnt attempting to replace streaming tools all together. Also didnt know it took that much bandwidth. Keep up the good work!

**Comment by no-connections** [comment]
I have tested with earlier versions over ZeroTier and it works but ofc will have implications on how you use the bandwidth. But it's and option of you need it.
