### ISSUE TITLE
video feed has started to freeze on the receiving end

### ISSUE THREAD

**Issue by kminooie** [fzwoch/obs-teleport#38]
So I installed teleport 2 days ago for the first time and was able to send my webcam and mic feed from my laptop (fedora 35) over wifi to my desktop (fedora 36)  on which I was capturing my game and stream the whole thing with out any issue. It was great.

Then, next day, the only thing that was changed on any of these system was that I ran a 'dnf update' on my laptop ( the sending system ) during which the following packages have been updated:
[dnf_update_list.txt](https://github.com/fzwoch/obs-teleport/files/8953409/dnf_update_list.txt)

Since then what happens is that once I start both obs applications ( doesn't matter in which order ), on the receiving system, I start seeing the feed just fine at first but it almost immediately start lagging and then goes to full freeze. The whole thing happens in about 2-3 seconds. The video gets update by one frame, a recent frame, once every minute or so. The audio feed thou is fine. I didn't see anything noticeable in the obs log files and the reports that gets dump once I close the obs on either side says that none of the frames have been dropped. I attached the log from the sending system ( laptop ):
[2022-06-20 21-44-38.txt](https://github.com/fzwoch/obs-teleport/files/8953397/2022-06-20.21-44-38.txt)

I also can see about 2.4 MB/s on the network ( system monitor ) continuously even when, on the receiving system, feeds looks frozen. my web cam output is 640x480@30 fps. Again audio keeps coming through fine.

I have restarted both system multiple time, closed all the other applications, removed the video capture src from the sending system and created a new one, but nothing changed. I'll be happy to provide more data if you tell me how to collect them. Also if you know any of the packages in the list is a dependency for obs or teleport I can try to revert it back and see if that fixes the issue.

I also have amd graphic drivers on both system, 4650g  apu on laptop, and vega 56 on desktop.

**Comment by fzwoch** [comment]
Teleport has no external dependencies. Maybe the kernel upgrade did change something? The logs are very incomplete I cannot even see whether you use the output or the filter mode. Does it work with another source?

**Comment by kminooie** [comment]
So it seems like the issue is with my wifi. Apparently my access point is dying and is causing all sort of issues. It was just an unfortunate coincidence that it started to do that right when I started to play with teleport. Anyway, sorry for the trouble and thanks for the plugin ;).

**Comment by fzwoch** [comment]
These things can happen. It is quite hardware setup depending after all. Thanks for letting us know.
