### ISSUE TITLE
Framerate doesn't match when streaming

### ISSUE THREAD

**Issue by Dizis249** [fzwoch/obs-teleport#42]
I am using a dual-PC streaming setup with OBS to stream to Twitch using Teleport:

Both of the PCs have Output (Scaled) Resolution set to 1280x720 and the FPS value at 60.

Yet somehow my stream ends up as 720p50 rather than 720p60?

**Comment by fzwoch** [comment]
Where do you see that? between the machines? Make sure you setup is fast enough, bandwidth and CPU wise. How do you see it is 50? Teleport should not have an impact how the final stream is created..

**Comment by Dizis249** [comment]
I see it is 50 when looking back at the Twitch VOD and opening up the quality selection settings of the recording it says "720p50 (Source)".

Broadcasting pc has: RTX 3050 Ti (laptop version), Ryzen 5 5600H, 16 GB RAM. 

Gaming pc has: RTX 3070, i5-10400F CPU, 32 GB RAM.

Connection speeds are: 100 Mbps download, 40 Mbps upload and both computers are connected with a cat8 cable.

**Comment by fzwoch** [comment]
And thats does not happen when the teleport source is not there?

Can you check with a local recording and `ffprobe` utility?

**Comment by Dizis249** [comment]
It seems to happen even without using Teleport lately. I believe it is because of having too many dropped frames in the stream.
