### ISSUE TITLE
Overall FPS performance drop.

### ISSUE THREAD

**Issue by ItsVinnyX** [fzwoch/obs-teleport#44]
I am unsure if I have Teleport setup incorrectly, but I notice a major performance drop making most of my games unplayable. Not sure how to fix it either. I go from 70-100 FPS while playing without teleport then to 30-40 FPS when teleport enables. There's got to be a way to fix this. My machine is pretty decent as well.

Specifications:
Intel i9-10850K
32 GB DDR4 RAM
GPU: RTX 3090 Ti

**Comment by fzwoch** [comment]
Closing as it may just be GTA doing some stuff. We don't try to impact perfomance im amy way - bit of course the processing power is being utilized by this plugin.
