### ISSUE TITLE
Black frames when switching scenes

### ISSUE THREAD

**Issue by timokorkalainen** [fzwoch/obs-teleport#47]
I tried Teleport as a substitute for OBS NDI and while it otherwise works fine, at least the latest version (0.5.0) seems to produce a black frame into the source output when switching between scenes with Teleport sources. This happens even if all the sources are visible in multiview and thus being sent and received while switching. Anything I'm missing?

**Comment by YorVeX** [comment]
You're not giving much information here. Screenshot showing that problem? OBS Version? Operating system? Teleport quality setting (default 90 or something else)? Resolution and FPS?

**Comment by fzwoch** [comment]
Especially easy to reproduce instructions. I'm not super family with all of OBSs features.

May have changed behavior with 549a5e59d9e523de2309c341ea15b97e2b65ad19.

**Comment by fzwoch** [comment]
Should be fixed with https://github.com/fzwoch/obs-teleport/releases/tag/0.6.0
