### ISSUE TITLE
No streams available — NixOS / macOS

### ISSUE THREAD

**Issue by kuzzmi** [fzwoch/obs-teleport#48]
Please tell me what additional information is needed to properly debug this issue.

I have installed Teleport both on NixOS (A) and on macOS (B) systems and can make them work with each other.

On (A) nothing happens when I press "Refresh List" in the list of streams, however everything else seams to "function": the Teleport filter is there, the Teleport source is available, I can turn Teleport on and set an identifier, and moreover, on (B) I can see this machine available, but there is no video/audio feed.

They both are connected to the same network and can see each other by other means, e.g., ssh.

**Comment by fzwoch** [comment]
Did you follow the README? Did you enable Teleport? As a filter or output via tools?

I guess if the services can be discovered the network seems fine. If the receiving part does not get and feed when subscribed to the service then it is most likely a firewall issue on the sender side disallowing a remote connection.

**Comment by kuzzmi** [comment]
@fzwoch, yes. I tried both — a filter on a source, and an output via tools. Both are visible on a macOS device, but neither of them produce any content. I've tried to disable firewall on both devices, nothing changed.

On the same note, nothing happens on NixOS device, when I press on “Refresh List” button:
![image](https://user-images.githubusercontent.com/1727140/184604040-0e76b892-dd49-40bb-a680-86f85171b762.png)

**Comment by fzwoch** [comment]
It sounds odd that on the device that offers a source there is nothing in the list. It should advertise itself on all interfaces it finds via multicast. Then again I have no idea about the network setup that may eventually make that approach fail.

**Comment by kuzzmi** [comment]
@fzwoch I'd say it's something else. If I turn off all advertisement everywhere completely, on the macOS device I see a word “- Disabled -” after clicking “Refresh”, but that's not the case on NixOS device.

**Comment by fzwoch** [comment]
I guess this can be closed?
