### ISSUE TITLE
[Feature Request] Stand alone version of Teleport

### ISSUE THREAD

**Issue by NyaomiDEV** [fzwoch/obs-teleport#49]
I wonder if Teleport can be made into its own thing that can stream whatever feed is fed into it via stdin. This could be awesome to stream, for example, a Steam Deck to an OBS instance, without requiring OBS itself on the Deck. Teleport could act as a simple daemon which is fed the screen feed, for example by Ffmpeg.

Do you think it'd be a good feature to have?

**Comment by fzwoch** [comment]
Teleport is intended to be an easy to use NDI like functionality for OBS. Nothing more really.

Teleport does not bring anything special to the table that could not be done with FFMPEG itself. I would even argue everything here is much watered down implementation of things that are at the disposal of FFMPEG. I will definitely not try to compete here..
