### ISSUE TITLE
not able to receive from my macbook to windows

### ISSUE THREAD

**Issue by TwanLuttik** [fzwoch/obs-teleport#50]
So i'm trying to receive my macbook teleport on my windows machine, I have allowed incoming traffic on port 85 on my windows machine in the firewall rules.

i also tried a different port but have no success yet.

Macbook
![CleanShot 2022-08-31 at 18 28 48](https://user-images.githubusercontent.com/19343894/187813010-5855fa23-b8c7-4548-8e88-3e1a1be630ba.png)

Windows
![CleanShot 2022-08-31 at 18 29 46](https://user-images.githubusercontent.com/19343894/187813138-50ce8292-05da-4016-abde-5b6d5c2ebe47.png)

port 85 from macbook
![CleanShot 2022-08-31 at 18 31 25](https://user-images.githubusercontent.com/19343894/187813305-5d0132bd-820c-41a3-adf5-18b9581fb92f.png)

**Comment by TwanLuttik** [comment]
but i'm able to receive my windows teleport on my macbook obs

**Comment by YorVeX** [comment]
> So i'm trying to receive my macbook teleport on my windows machine, I have allowed incoming traffic on port 85 on my windows machine in the firewall rules.

You got it backwards then though. The port you configure the is the port the sender machine is offering the Teleport stream on for any potential receivers to grab it from. If the MacBook is your sender and you configure port 85 there, then the MacBookis listening on port 85 and the Windows machine being the receiver would try to connect to port 85 on the MacBook. That means you need to open port 85 in the firewall on the MacBook.

Also I wouldn't recommend to use port numbers < 1024, I am not familiar with Macs but many operating systems have those reserved for certain things, some firewalls don't even allow to open ports in that range when it's done for user level (or only if certain advanced settings are used and this behavior is actively overriden). To be on the safe side I'd always use a 5 digit port number.

**Comment by TwanLuttik** [comment]
@YorVeX 

So i changed to port 10505 which didn't help but just to be safe as you say and also on my windows machine as incoming TCP rules on the firewall, i have changed the protocol from TCP to any and it seems be showing my macbook in the list


<img width="300" alt="CleanShot 2022-08-31 at 18 53 16@2x" src="https://user-images.githubusercontent.com/19343894/187815521-5d7e81da-7ad5-4258-b5c2-59d1ea520131.png">

<img width="448" alt="CleanShot 2022-08-31 at 18 56 33@2x" src="https://user-images.githubusercontent.com/19343894/187816131-d98b5cd9-d6c0-48f9-acb3-5015e89720ca.png">

And it seems to be working now after that firewall protocol change to any

![CleanShot 2022-08-31 at 19 00 54@2x](https://user-images.githubusercontent.com/19343894/187816441-1cff0c65-509d-4c39-b1f8-603df4afaa22.png)

**Comment by fzwoch** [comment]
Thanks for joining in YorVeX. I believe this can be closed.
