### ISSUE TITLE
OBS V28 support

### ISSUE THREAD

**Issue by TwanLuttik** [fzwoch/obs-teleport#51]
I have removed the plugin and tried to re install the plugin from its macos folder with `bash install.command` and also tried with sudo `sudo bash install.command` but i guess the plugin has to be updated to its new version.

I heard many of the plugins won't work until they are updated with this new release

**Comment by fzwoch** [comment]
If you are talking about Apple M1 support, this is blocked by #43.

So it is actually a convenience that the plugin does not load on OBS 28 in its current form as it would do more harm if it would.

**Comment by TwanLuttik** [comment]
Okay, because i'm on the m1 macbook and before OBS 28 it did work

**Comment by fzwoch** [comment]
Sure, run OBS 28 x86_64 under Rosetta and it will still work.

**Comment by fzwoch** [comment]
Close because of the main issue being #43.
