### ISSUE TITLE
OBS Studio crashing on mac

### ISSUE THREAD

**Issue by miggy3399** [fzwoch/obs-teleport#52]
Good day. I attempted to install teleport on my mac (OS High Sierra) but now my obs studio continues to crash when I try to open it

Is there something I missed during the installation process? Thank you

**Comment by fzwoch** [comment]
Hard to say without a crash log.

Does it crash when opening OBS? Did you set up Teleport and it crashes when sending or receving?

**Comment by miggy3399** [comment]
Nevermind. I got it to work. My defective eyes didn't notice that the obs
version I was using was incompatible with the current version of Teleport.
Thanks for the reply though

**Comment by fzwoch** [comment]
Out of curiosity, what version was it? (And why is it not compatible)

**Comment by miggy3399** [comment]
My OBS version was version 23. Then I downloaded version 27 to make it
compatible

**Comment by fzwoch** [comment]
Thanks, that makes sense. 23 is quite old and I think there has been a change in the plugin API since that makes it incompatible.
