### ISSUE TITLE
OBS Studio V28.0.2 colors it all green on the recieving end

### ISSUE THREAD

**Issue by jimthesfn** [fzwoch/obs-teleport#54]
Hi,
it seems with the v28.0.2 update the streaming PC that recieves the teleport stream from the gaming PC is all green colored(see attached picture). It looks fine on the preview window on the gaming PC but on the streaming PC it is all green (see attached picture).
I went back to v28.0.1 and no issues there.
![greentint](https://user-images.githubusercontent.com/55837922/192003168-a2805185-1d20-44b5-9c82-ad92cc0e2fe9.png)

**Comment by Chaniro** [comment]
same issue here

**Comment by fzwoch** [comment]
Is that possibly related to https://github.com/obsproject/obs-studio/issues/7442?

**Comment by Fenrirthviti** [comment]
Yes, this is a bug introduced in 28.0.2, we've (OBS) identified it and are working on a fix. Not a bug with this plugin!

**Comment by fzwoch** [comment]
Thanks for the confirmation, I'll leave this upon in case someone stumbles upon the same issue until a fix is released.

**Comment by fzwoch** [comment]
Looks like 28.0.3 is out.
