### ISSUE TITLE
[Crash] Teleport issue with OBS 28.0.3

### ISSUE THREAD

**Issue by VictorKruger** [fzwoch/obs-teleport#56]
Hi,

The current version of obs-teleport is causing obs version 28.0.3 to close out without error in linux.  The crash will occur between 30 - 60 minutes when streaming.  I verified that it is obs-teleport by setting up a test stream without obs-teleport which ran for 2+ hours without issue and then ran a second test stream which obs closed down around 40 minutes in.  I've attached a gdb debug and the log file for obs when it closed.  

Please let me know if you need anything else.
```
System info:
System:
  Kernel: 5.15.0-48-generic x86_64 bits: 64 compiler: gcc v: 11.2.0 Desktop: Cinnamon 5.4.12
    tk: GTK 3.24.33 wm: Mutter dm: LightDM Distro: Linux Mint 21 Vanessa base: Ubuntu 22.04 jammy
Machine:
  Type: Desktop Mobo: MSI model: X99S SLI PLUS (MS-7885) v: 1.0 serial: <superuser required>
    UEFI: American Megatrends v: 1.F2 date: 06/13/2019
CPU:
  Info: 6-core model: Intel Core i7-5930K bits: 64 type: MT MCP arch: Haswell rev: 2 cache:
    L1: 384 KiB L2: 1.5 MiB L3: 15 MiB
  Speed (MHz): avg: 3263 high: 3501 min/max: 1200/3500 cores: 1: 3500 2: 3077 3: 1860 4: 3501
    5: 3500 6: 3500 7: 3500 8: 3252 9: 3375 10: 3336 11: 3306 12: 3460 bogomips: 83995
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: NVIDIA GA104 [GeForce RTX 3070] vendor: eVga.com. driver: nvidia v: 515.76 pcie:
    speed: 8 GT/s lanes: 16 ports: active: none off: DP-2,DP-3 empty: DP-1,HDMI-A-1 bus-ID: 02:00.0
    chip-ID: 10de:2484
  Device-2: Blackmagic Design Intensity Pro driver: N/A pcie: speed: 2.5 GT/s lanes: 1
    bus-ID: 06:00.0 chip-ID: bdbd:a117
  Device-3: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo
    bus-ID: 5-1.4.1.1:7 chip-ID: 046d:082d
  Device-4: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo
    bus-ID: 5-1.4.1.4:8 chip-ID: 046d:08e5
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia gpu: nvidia display-ID: :0
    screens: 1
  Screen-1: 0 s-res: 4000x2560 s-dpi: 96
  Monitor-1: DP-2 pos: primary,bottom-r res: 2560x1440 dpi: 65024 diag: 1mm (0.1")
  Monitor-2: DP-4 pos: primary,top-left res: 1440x2560 dpi: 36576 diag: 1mm (0.1")
  OpenGL: renderer: NVIDIA GeForce RTX 3070/PCIe/SSE2 v: 4.6.0 NVIDIA 515.76 direct render: Yes
Audio:
  Device-1: NVIDIA GA104 High Definition Audio vendor: eVga.com. driver: snd_hda_intel v: kernel
    pcie: speed: 8 GT/s lanes: 16 bus-ID: 02:00.1 chip-ID: 10de:228b
  Device-2: Blackmagic Design Intensity Pro driver: N/A pcie: speed: 2.5 GT/s lanes: 1
    bus-ID: 06:00.0 chip-ID: bdbd:a117
  Device-3: C-Media OriGen G2 type: USB driver: hid-generic,snd-usb-audio,usbhid bus-ID: 5-1.2:3
    chip-ID: 0d8c:0319
  Device-4: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo
    bus-ID: 5-1.4.1.1:7 chip-ID: 046d:082d
  Device-5: Logitech HD Pro Webcam C920 type: USB driver: snd-usb-audio,uvcvideo
    bus-ID: 5-1.4.1.4:8 chip-ID: 046d:08e5
  Device-6: Jieli USB Composite Device type: USB
    driver: hid-generic,snd-usb-audio,usb-storage,usbhid bus-ID: 5-1.4.4:6 chip-ID: 4c4a:4155
  Sound Server-1: ALSA v: k5.15.0-48-generic running: yes
  Sound Server-2: JACK v: 1.9.20 running: no
  Sound Server-3: PulseAudio v: 15.99.1 running: yes
  Sound Server-4: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Ethernet I218-V vendor: Micro-Star MSI driver: e1000e v: kernel port: f000
    bus-ID: 00:19.0 chip-ID: 8086:15a1
  IF: eno1 state: down mac: <filter>
  Device-2: Mellanox MT27500 Family [ConnectX-3] driver: mlx4_core v: 4.0-0 pcie: speed: 8 GT/s
    lanes: 4 port: N/A bus-ID: 01:00.0 chip-ID: 15b3:1003
  IF: ens2 state: up speed: 10000 Mbps duplex: full mac: <filter>
  IF-ID-1: virbr0 state: down mac: <filter>
Drives:
  Local Storage: total: 232.89 GiB used: 193.89 GiB (83.3%)

  ID-1: /dev/sda vendor: Samsung model: SSD 850 EVO 250GB size: 232.89 GiB speed: 6.0 Gb/s
    serial: <filter>
```

[GDB teleport debug.txt](https://github.com/fzwoch/obs-teleport/files/9747568/GDB.teleport.debug.txt)
[2022-10-09 16-28-04.txt](https://github.com/fzwoch/obs-teleport/files/9747556/2022-10-09.16-28-04.txt)

**Comment by fzwoch** [comment]
```
obs: ./libobs/util/circlebuf.h:246: circlebuf_peek_front: Assertion `size <= cb->size' failed.
```

Is it the sender or receiver that is crashing?

It may be Teleport triggering it, but it is the internal ring buffer of OBS triggering an assertion it seems. Eventually a frame with 0 length was send to the ring buffer.

a) A release version of OBS should probably not throw on assertions? But not sure if it would crash then in other areas as a result. Do you run a debug version of OBS?

b) Try the attached version of Teleport. You will need to update sender and receiver instances of Teleport because the protocol has slightly changed. Let me know if that one still exhibits the issue.

[test.zip](https://github.com/fzwoch/obs-teleport/files/9747836/test.zip)

**Comment by VictorKruger** [comment]
Hi,

It is the receiver that is crashing.  I was using the standard release of OBS version 28.0.3, I just attached a debugger to the executable using GDB.  I'll give the attached version a test and see if that works.

I'll let you know the results as soon as I get them.

Thanks!

**Comment by VictorKruger** [comment]
The test version of your plug-in worked!  No crashes or anything in a 2+ hour test stream.  

Thank you again for the quick response and the test build of your plug-in!

**Comment by fzwoch** [comment]
Thanks. I guess this means release time. I hope it does not break anything
else as this one was quite some overhaul.

VictorKruger ***@***.***> schrieb am Di., 11. Okt. 2022,
05:37:

**Comment by fzwoch** [comment]
Hopefully fixed with https://github.com/fzwoch/obs-teleport/releases/tag/0.6.0
