### ISSUE TITLE
No properties in OBS 27

### ISSUE THREAD

**Issue by Corben78** [fzwoch/obs-teleport#57]
Just upgraded to teleport 0.6.0, but I don't have any teleport settings anymore.

The logfile states:
```
19:04:25.394: [obs-teleport] Version 0.6.0
[...]
19:04:25.410: ---------------------------------
19:04:25.410:   Loaded Modules:
19:04:25.410:     obs-teleport.so
[...]
19:04:28.421: Source ID 'teleport-dummy' not found
19:04:28.421: Failed to create source 'Teleport'!
```
On my test machine with OBS 28 it works, but currently I cannot upgrade on the other machine.

**Comment by Mrpipdarty** [comment]
I am personally having the same issues

**Comment by fzwoch** [comment]
From what version did you upgrade? `teleport-dummy` still exists but is not selectable. So if you managed to add it to a scene in a previous version you should somehow manually remove it from the OBS config file.

0.6.0 also was updated to use OBS 28 headers. I have no idea whether these are supposed to be loadable by OBS 27 or not.

**Comment by Corben78** [comment]
I had 0.5.0 before and downgraded again. Will check if removing all Teleport sources helps.
But if 0.6.0 will have OBS 28 as minimum requirement, I guess I'll have to stick to 0.5.0 anyways.

**Comment by fzwoch** [comment]
Please re-download the 0.6.0 release. It should be updated to run on OBS 27 as well.

**Comment by fzwoch** [comment]
.. and re-open this issue if it still does not work..

**Comment by Corben78** [comment]
Used it today for 8.5 hours, worked as it should! Thanks so much!
