### ISSUE TITLE
Teleport displays nothing even though it is connected to transmitter.

### ISSUE THREAD

**Issue by ScottVordem** [fzwoch/obs-teleport#58]
I have OBS Studio installed with the Teleport plugin on Manjaro Linux. Everything is working correctly.

I have OBS Studio installed with the Teleport plugin on Windows 10 21H2. Everything is working correctly.

I have the Windows PC as the transmitter and Manjaro as the receiver. I turn on the transmitter in windows and try to connect it to OBS on Manjaro. I add a Teleport source on Manjaro and the instance from the Windows PC does show up on the list, but upon selecting it, displays nothing. The Windows OBS has a Display Capture source visible, but Teleport on Manjaro displays nothing even though it is connected to the Teleport instance.

Swapping the setup (making Manjaro the Transmitter and Windows the receiver) The Manjaro instance does not even appear in the list on Windows.

Both computers are on the same network and I have Manjaro's Firewall turned off, so I don't know what exactly the issue is or which computer is at fault.

I have an unusual internet setup for Manjaro. It does not have a wireless Wi-Fi card but has an Ethernet port, but the area I am in has no port available to plug into the router. I have the Windows PC sharing its Wi-Fi connection through its Ethernet port, to the Ethernet port on the Manjaro machine, so Manjaro is getting internet through the Windows PC. Would that have something to do with it?

**Comment by fzwoch** [comment]
Most likely it is the activated Windows firewall. I other weird things are going on on your network I cannot tell. That's up to you to find out.
