### ISSUE TITLE
ParrotOS

### ISSUE THREAD

**Issue by NAngryPole** [fzwoch/obs-teleport#60]
Anyone get this working on ParrotOS? I went back to version 4.7 and what ends up happening is OBS fails to open with no error. Once i remove the plugin from the folder OBS loads without issue.

/.config/obs-studio/plugins

Tried manually moving and running install.sh

Using files from Teleport folder;
Linux-x86_64

**Comment by fzwoch** [comment]
4.7 of what? Parrot OS? Looks a bit outdated, I guess it runs an old version of OBS. Possibly the pre-compiled version does not fit.

**Comment by NAngryPole** [comment]
Sorry no i meant 4.7 of the teleport plugin from the releases section.

**Comment by NAngryPole** [comment]
I have it running on Windows 10 no problem. Was just curious if you ever ran it on a Debian based Linux machine and ran into an issue like this.

**Comment by fzwoch** [comment]
Why not use the latest version of this plugin? This plugin is being developed primarily on a Debian machine.

**Comment by fzwoch** [comment]
You should least try running OBS from the command line to see it it says a reason for crashing. And if it is crashing - do a stack trace.

**Comment by NAngryPole** [comment]
> Why not use the latest version of this plugin? This plugin is being developed primarily on a Debian machine.

I tested the newest first when it started crashing. I tried manually moving the plugin to the plugins folder and running install.sh

**Comment by fzwoch** [comment]
No logs, no traces. Closing.
