### ISSUE TITLE
Suspicious detection by VirusTotal

### ISSUE THREAD

**Issue by SilkyZielke** [fzwoch/obs-teleport#62]
Possible Trapmine detection on teleport.exe - 22 MITRE Tactics found

Hoping someone can confirm the use of the Defense evasion tactics, and the use of the reported network traffic. 

Basic Properties
MD5	d48af69f2dd5aa9472206681ef264fc1
SHA-1	9cc6dc7d14203dbdf0309278d204fc221e793dc7
SHA-256	eac092e7ea78f14653cdcb3e194722afc83897145f458b01052d56634d50265e
Vhash	[0160966d1575151c0d1d00d043z800417z47z72z3ffz]
Authentihash	[0861445d4201e9351c6ac32f413545a80083ec0f6795b564f4a6066c63b28064]
Imphash	[6169175a0a7af2b9c8a2e2eac3911bf6]
SSDEEP	[24576:DuTEOZ8y7lEwEAc6JNPty6VqnIwQ2lqefAiX/1ghbnuMt6+HoCG:WuyZt7htyHRIiP1Inuu19G]
TLSH	[T17B653324E3AB9CFDC82719B548DF7727F5617C48A1E992671BC122B71C3EB80D91AE40]

**Comment by fzwoch** [comment]
Could be due to NSIS installer. But contact VirusTotal about this.
