### ISSUE TITLE
lost frames/audio skips

### ISSUE THREAD

**Issue by ImperialTazer** [fzwoch/obs-teleport#67]
Its not an obs problem, as theres no loss during streaming it, the stats are all good. 

There is an issue that started happening where somewhere in the transfer between obs's, there are skipped frames and audio. I havent seen anything on any forums. My internet is 500, soon to be 1 GB, so I wouldn't think thats the issue. I had a worse problem of stuttering that was happening, but I fixed that by changing the output to a 9:6 ratio instead of 1920x1080. It was working great until yesterday. Now the audio and frame lag/ stutter is making my stream look so bad. Is there any reccomended steps to take to fix this?

Heres and example of when I was dealing with it. https://www.twitch.tv/videos/1739343962 
Like I said before, once i refreshed my stats, because I was thinking it was an obs thing, the stats were good, I was noticing the lag and audio skips and such in the teleport audio input. Ive been using teleport for a month without this issue, and I love using it, but cant with how bad this skipping is! 

Let me know if there is anything you need to help asses this

**Comment by fzwoch** [comment]
Internet speed is not relevant for Teleport. If it has been working fine for a Month you must have changed something. Either the machine or LAN speed is impacted. But that is nothing this plugin can fix.
