### ISSUE TITLE
Cannot add Teleport filter to source clone and some other sources.

### ISSUE THREAD

**Issue by no-connections** [fzwoch/obs-teleport#68]
"User added filter 'Teleport' (teleport-filter) to source 'Source Clone'" 
but no filter is added. Also tested with browser source same result.
"User added filter 'Teleport' (teleport-filter) to source 'Browser'"

Both Teleport and Teleport(Video) behaves this way.
Teleport(Audio) works. 

Media Source seems to work fine fine.

v29.0.2 and Teleport 0.6.5

**Comment by fzwoch** [comment]
Teleport does only work for async sources. Browser source iirc is not one of them. If the filters are listed it is a bug in OBS imho.

https://github.com/obsproject/obs-studio/commit/aee268c9443cb39f3823886d475fa24f848f69ab may have addressed it. at least I don't see it listed on my end when trying to select it as filter to an image source.

**Comment by no-connections** [comment]
I vaguely feel like I shuold remember that from somewhere.
Yes it shows up in the list for me, so it should be patched in next OBS release I guess.

"OBS Asynchronous Source Duplication" to clone "Source Clone" seem to work as a strange workaround if I need it for something.
