### ISSUE TITLE
Disable Audio?

### ISSUE THREAD

**Issue by DocMAX** [fzwoch/obs-teleport#69]
Can audio be completly disabled?

**Comment by DocMAX** [comment]
I mean disable completly to save bandwidth.

**Comment by fzwoch** [comment]
No. If bandwidth is a concern this is probably the wrong direction to look any way.
Stereo audio is about 1.4 mbit/s while your video will be in the 200-300 mbit/s.

Depending on your source, there is a video only variant when used in filter mode.
