### ISSUE TITLE
teleport wont broadcastNET on MacOS

### ISSUE THREAD

**Issue by riku2015** [fzwoch/obs-teleport#70]
teleport wont broadcast to network on MacOS serverside, port is open and it is working, i read there is no allowed net at all broadcasting on mac.
Solution to this problem is add manual ip:port at client side to allow connect with ip. as there is no way to do that now, it cannot be connected.

Connection as localhost works fine, and connection other direction works fine too. firewalls are disabled.

teleport 0.6.5
os 12.6
obs 29.0.2

**Comment by fzwoch** [comment]
This seems more like a support request than a bug report. I cannot help you with your network. So far it has been working fine on macOS.
