### ISSUE TITLE
Can't set Teleport filter on Game Capture and/or Display Capture

### ISSUE THREAD

**Issue by rickvanoverbeek** [fzwoch/obs-teleport#74]
When I use Game Capture and/or Display Capture, I can't set Teleport as the Audio/Video Filter. It only allows me to set an Effects Filter.

**Comment by YorVeX** [comment]
At least for me these sources only support effect filters in general so of course you can't set Teleport (or any other filter) as A/V filter for them.

![image](https://user-images.githubusercontent.com/528974/232253706-dbcc872e-e3a9-41dc-99cd-05c28e41c368.png)

Is it different for you? What version of OBS and Teleport are you using?

**Comment by rickvanoverbeek** [comment]
No it's exactly the same for me. I'm using the latest OBS and Teleport version.
Want I want to do is, stream my gaming PC video and audio from my 14" MacBook Pro M1 Pro.

But since Display Capture and Game Capture both aren't supporting Teleport, how can I get my game video and audio from my gaming PC to my MacBook?

**Comment by YorVeX** [comment]
Can't you just use the standard output? You configure that from OBS main menu -> Tools -> Teleport. The filter solution is only meant for special use cases where you really only want to stream a separate source, e.g. I use this to send my shoulder cam feed separately so I can separately toggle/arrange it on the streaming PC.

If you really need to use the filter I think a workaround was to create a clone of the Display or Game Capture source first using [this plugin](https://obsproject.com/forum/resources/source-clone.1632/) and then applying the Teleport filter to the cloned source.

**Comment by fzwoch** [comment]
As stated, effect filter mode is not supported as the texture is on the GPU. Unless someone provides code for copying this back I won't add it. Also I believe this is discouraged as it will impact performance for those sources.
