### ISSUE TITLE
Comparision to OBS-NDI plugin

### ISSUE THREAD

**Issue by Joly0** [fzwoch/obs-teleport#76]
Hey, i am interested in this, but it would be great to have some more information on how this works, why i should use it instead of the obs-ndi plugin, what makes it better, what are lacks of features and so on in the readme or somewhere else.

**Comment by fzwoch** [comment]
No one said you should use it instead of NDI. Try both, decide for yourself.

I don't even know NDI that well myself. Compared to NDI this one is open source.

**Comment by YorVeX** [comment]
Maybe something from my own experience, that is of course very subjective and tight to my specific setup: CPU load is a little higher than it is with NDI, but A/V sync stability is a lot better, which is why I switched to Teleport in the first place, with NDI this was horrible.

**Comment by Joly0** [comment]
> No one said you should use it instead of NDI. Try both, decide for yourself.
> 
> I don't even know NDI that well myself. Compared to NDI this one is open source.

I know, noone said i should use it, but i question what might be a reason to use this plugin compared to ndi? Is it "just" the open source aspect? 
Thats a valid reason, but if the ndi plugin works for me, are there any reasons to switch? Thats what i am asking

**Comment by Joly0** [comment]
> Maybe something from my own experience, that is of course very subjective and tied to my specific setup: CPU load is a little higher than it is with NDI, but A/V sync stability is a lot better, which is why I switched to Teleport in the first place, with NDI this was horrible.

Thats some reasoning i was seeking for. Thank you
