### ISSUE TITLE
Bandwidht for 1080/60fps?

### ISSUE THREAD

**Issue by banquer** [fzwoch/obs-teleport#78]
What a gretat wrok mate!!
I own a Gb local network and use teleport to capture replay game in a two pc setup for simracing.
I'm studing to upgrade my switch and nics to 2.5Gb or 10Gb network if this improve the quality of the de record.
How many bandwidth do I need for best quality in 1080/60fps capture?
You can see in this video what  I do.
https://youtu.be/AiVc-l0OPOk?t=3671
Many thanks in advance!!

**Comment by fzwoch** [comment]
That very much depends on the quality you set for transmission and the content you are transferring. I have no data at hand, but you should be able to just test it out?

If you don't mind the cost for upgrading, perhaps you want to check out https://obsproject.com/forum/resources/xobsbeam-beta.1705/ too. It allows lossless transmission.

**Comment by fzwoch** [comment]
On the sending machine check the Teleport properties. It has a quality slider ranging from 0 to 100. This basically a quality/bandwidth/cpu-usage control. The higher the quality the more bandwidth and probably cpu usage is going to be used. Find your personal sweet spot with this slider. For 1080p60 i would the bandwidth to be around 350mbps perhaps(?) even at quality set to 100. Check if you are okay with the increased cpu usage.

**Comment by banquer** [comment]
Ok. No matter the options in streaming encoding in sender. Only the slider in teleport settings.
Many thanks Fllorian!
