### ISSUE TITLE
Stream only discoverable from one direction and not the other

### ISSUE THREAD

**Issue by inator0** [fzwoch/obs-teleport#79]
There are 2 Windows machines named `A` (Win 11) and `B` (Win 10). The machines can ping each other. Firewall is disabled on both machines. 

Problem:
Teleport only works in one direction, from A to B, it needs to work in the other direction, i.e. B to A. This was working until a few days ago so it is likely an issue on my end but I lack visibility into what's happening with teleport. Does teleport have additional logging for troubleshooting further?

Log from `A` (Win 11):
[https://obsproject.com/logs/TZM9GfszfPy6nmYk](https://obsproject.com/logs/TZM9GfszfPy6nmYk)

Log from `B` (Win 10):
[https://obsproject.com/logs/oPCnApxpsfPOUV6P](https://obsproject.com/logs/oPCnApxpsfPOUV6P)

This is what the teleport configuration looks like:
![image](https://github.com/fzwoch/obs-teleport/assets/137371440/b9f091ea-a293-4a96-bc5c-26e659972b20)

Network test output:
```
PS C:\Users\me> Test-NetConnection -ComputerName 192.168.0.BBB -Port 11222


ComputerName     : 192.168.0.BBB
RemoteAddress    : 192.168.0.BBB
RemotePort       : 11222
InterfaceAlias   : Wi-Fi
SourceAddress    : 192.168.0.AAA
TcpTestSucceeded : True



PS C:\Users\me> ping 192.168.0.BBB

Pinging 192.168.0.BBB with 32 bytes of data:
Reply from 192.168.0.BBB: bytes=32 time<1ms TTL=128
Reply from 192.168.0.BBB: bytes=32 time=1ms TTL=128
Reply from 192.168.0.BBB: bytes=32 time=11ms TTL=128
Reply from 192.168.0.BBB: bytes=32 time=2ms TTL=128

Ping statistics for 192.168.0.xxx:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 0ms, Maximum = 11ms, Average = 3ms
```

**Comment by fzwoch** [comment]
Well.. figure out what has changed :-)

Discovery is UDP multicast. So it is connection-less. Hard to log anything in this case if it just isn't there. Iirc the mulitcast announce is send on all available interfaces. So either it isn't doing it properly, or perhaps your router does not forward these packets from Wifi to LAN or vice versa.

**Comment by YorVeX** [comment]
You could try to find a separate UDP tool to rule out whether it's a problem with Teleport - I'd say it's unlikely, especially when it worked for you before, but you never know. But when that shows the same behavior you know as much as before, that one way the UDP packet is received and the other way it's not, any logging would also only show you that a packet is received or nothing if nothing is received.

The easiest way to solve this would be really if you could find out what has changed recently. Maybe you upgraded router firmware, or if it's a router rented from your ISP they pushed an update to it without you even knowing? Did you change the cabling, network drivers (+ settings), WiFi settings, network hardware? If you have a switch within your network, many of them (especially the cheap ones that most of us use at home) just can't transmit UDP broadcasts, although in that case I'd assume it wouldn't work in any direction.

**Comment by inator0** [comment]
The main recent change was some OBS encoding settings and software/plugin updates. Nothing networking related, not intentionally anyway. I thought maybe something went wrong with Teleport during the update process. A clean install of OBS didn't help.

I've tried an external UDP multicast testing utility and that didn't work. Testing on a 3rd machine, Teleport has no issues on wifi. So that should rule out networking hardware and Teleport itself as the problem. 

Now that I know it might be an issue with UDP multicast, I will dig further to find out what's going on with the machine. This was very helpful, thank you so much for the suggestions.
