### ISSUE TITLE
teleporting from a PC to Macbook ( intel-not silicone)

### ISSUE THREAD

**Issue by Opus-greybeard** [fzwoch/obs-teleport#80]
IS there an issue running teleport on a PC and a MAC together, it was easy setup on pc, but installing the mac os version seems problematic or im missing something, Shouldnt there be an .SO file all i get is the install command for terminal and the plugin as 2 files. Running the command does nothing, created a folder in plugins and copied the plugin, still not detecting the plugin in OBS. Didn't understand where to go for support, so apologies if im at the wrong spot ( github newbie)

**Comment by fzwoch** [comment]
You can right-click on the `.plugin` file and select `Show Package Contents` which in the end points you to the binary. But this format is the required one for newer OBS versions.

You may need to tell macOS's Gate Keeper to allow loading this plugin (required twice, upon install command and then upon OBS launch).

It works fine for me when I run it under Rosetta.

**Comment by Opus-greybeard** [comment]
ok, im running OBS 22.0.3 on the mac with catalina OS might there be something there, I tried everything I can think off, but teleport just wont show up as a source in macos. When i opened the file in show package there was a 6.5 mb textfile and a info.plist

**Comment by fzwoch** [comment]
OBS 22?! Teleport will require OBS 28 as a minimum iirc.

**Comment by Opus-greybeard** [comment]
*solution was bootcamp, windows 10 and newest versions of OBS, works now, thx for the help and patience
