### ISSUE TITLE
the plugin dont work on linux

### ISSUE THREAD

**Issue by uranxo** [fzwoch/obs-teleport#82]
i installed the plugin on linux ubuntu, it installed correctly (i checked files into obs folder) but it dont work because if i try to look for it in the tool tab or in the sources tab it doesnt appear

**Comment by fzwoch** [comment]
- Check the log if there are any hints of a failure - does it even try to load.
- Make sure you have installed OBS v28 or later.
- Make sure you don't have Snap or Flatpak version of OBS - refer to them on how to install plugins.

**Comment by uranxo** [comment]
i found the solution, when I uninstalled the other versions, the files were not completely deleted and being files of different versions they created conflicts and the plugins did not work, then i uninstalled all the file in .config and now it works
