### ISSUE TITLE
Audio Only

### ISSUE THREAD

**Issue by Tomcatt** [fzwoch/obs-teleport#83]
Hello,

I'm really liking what I see about your version OBS-NDI.  Could you add an option for audio only?  I have lots of different audio sources that I control on the second machine.

Also, if users has more bandwidth on their network, could we increase the quality to 100%?  My network is1G, 10G and 40G.

**Comment by fzwoch** [comment]
There is audio only modes available when added Teleport as a filter on a source.

You can increase the quality to whatever you want. The complexity increase over the quality gain is just out of proportion.

**Comment by Tomcatt** [comment]
I found it.  Thank you.  I like the quality bar you have.  This is gold.  From what I can tell, I've turned it down and I can't hear any differences unless I plug in a scanner.

Now, if could slip in something that'll let me sync the audio with the video or delay the audio.  

I think you should be the new replacement for OBS-NDI.  OBS_Teleport just works.  Small learning curve and that's it.

I'm going to close this out.  You answered my main question.  The delay feather is under another thread.

**Comment by fzwoch** [comment]
Thanks! I think Teleport is just a subset of NDI. But that subset it aims to provide in a very easy way.

The quality slider is for video only. Audio is always transmit lossless/uncompressed. So if you experienced a difference the brain has lied to you! ;-)

**Comment by fzwoch** [comment]
A simply audio is probably completely standalone and hardly to sync to something arbitrary.

Maybe @YorVex has a hint, as I know he spent a lot of time an pain within OBS syncing..

**Comment by YorVeX** [comment]
Mostly pain, really. 🩸🩹💉

OP has already found the correct issue where I try to tackle this. Whether I will succeed is another question.
