### ISSUE TITLE
does not load properly in flatpak version...

### ISSUE THREAD

**Issue by mc711** [fzwoch/obs-teleport#85]
hi, i am trying to get this to load in the flatpak version of OBS. i am using a steam deck and loading the arch binary.

according to this, 

https://github.com/flathub/com.obsproject.Studio/wiki/Plugins#method-2-config-folder

for manual installation, i copy the required obs-teleport.so library into

/home/deck/.var/app/com.obsproject.Studio/config/obs-studio/plugins/

there is no error in the log, but there is no teleport under Tools.

if i load it according to the installation script into

/home/deck/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-teleport/bin/64bit/

i get error

os_dlopen(/home/deck/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-teleport/bin/64bit/obs-teleport.so->/home/deck/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-teleport/bin/64bit/obs-teleport.so): /home/deck/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-teleport/bin/64bit/obs-teleport.so: cannot open shared object file: No such file or directory
os_dlopen(/home/deck/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-teleport/bin/64bit/obs-teleport.so->/home/deck/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-teleport/bin/64bit/obs-teleport.so): /home/deck/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-teleport/bin/64bit/obs-teleport.so: cannot open shared object file: No such file or directory
Module '/home/deck/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-teleport/bin/64bit/obs-teleport.so' not loaded

any way to get this working?

**Comment by fzwoch** [comment]
I don't use Flatpak and don't have a steam deck. Technically there is no reason what it should not work imo.

Did you compile the plugin yourself? Did you pick the correct platform? I have no idea why it would complain about `No such file or directory`.

**Comment by MilkyMad** [comment]
@mc711 
Hello there. Been searching too for flatpak obs, works fine to me, tested with teleport plugin on Win11.
Downloaded from releases, done by full path after plugins folder.
`/home/_user_/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-teleport/bin/64bit/obs-teleport.so`

**Comment by mc711** [comment]
@fzwoch no, i used the pre-compiled from releases. i used the aarch binary since deck is based on arch linux.

ya, i am not sure why it gives that error either. ive checked permissions and everything. guess i will try to look for a solution or give up.

@MilkyMad ya, when i place it there it gives me the error. no idea what's wrong. might be a steamOS problem

**Comment by fzwoch** [comment]
> @fzwoch no, i used the pre-compiled from releases. i used the aarch binary since deck is based on arch linux.

Ugh.. no. `aarch64` means ARM64 platform in this context. The Steam Deck has a x86_64 CPU. So pick that one!

**Comment by mc711** [comment]
@fzwoch funny, first time i tried i was using the x86_64 but it wasn't working that's why i assumed it needed the aarch, but i tried again to be sure and it works now!
thanks for clarifying. linux can be very confusing.

anyways, for anyone else who encounters this problem.
extract `linux_x86_64/obs-teleport.so` to
`~/.var/app/com.obsproject.Studio/config/obs-studio/plugins/obs-teleport/bin/64bit/obs-teleport.so`
