### ISSUE TITLE
Video slomotion / audio cracking

### ISSUE THREAD

**Issue by TheApexDevil** [fzwoch/obs-teleport#87]
There seems to be a problem were on the streaming pc 
The video start going in slomotion after a hour and a half and th mic sound starts cracking

Even after restarting both the gaming and streaming pc this still doesnt fix it

One day you can stream for hours and the other day its a hour and half

(This was with a I7 9700k on the streaming pc NO GPU)

**Comment by fzwoch** [comment]
No GPU?
But it sounds like a network congestion.

**Comment by fzwoch** [comment]
The WAN speed is not relevant.
It depends on the LAN connection and behavior. Having Cat 7 cables doesn't not guarantee a  given throughput. There may be a million factors impacting the performance.
I don't think I can do much here if there is no reliable way of reproducing the issue.

**Comment by fzwoch** [comment]
Maybe your logs have a hint on whats happening. Until then I'll close this.
