### ISSUE TITLE
OBS can not open (not responding) when teleport is installed (Mac)

### ISSUE THREAD

**Issue by VallyIsHere** [fzwoch/obs-teleport#88]
Having an issue with OBS and teleport that I don't see any existing documentation on. When I try to open OBS with the teleport plug-in installed, OBS gets hung-up and can't open it just goes straight into "not responding" status, requiring me to Force Quit. When I remove the file "obs-teleport.plugin" from the plugin folder (Library > Application Support > obs-studio > plugins) or run OBS in safe mode, OBS opens fine.

OBS version 30.0.0
OSX Monterey 12.6
Teleport 0.7.0

I have tried opening OBS via control click > open, doesn't help me get past this.

I have allowed the Teleport plugin via system preferences > security & privacy > general tab

My firewall is off

**Comment by fzwoch** [comment]
Same as #43

**Comment by VallyIsHere** [comment]
ah thank you for the direction!
