### ISSUE TITLE
Possible flutter integration?

### ISSUE THREAD

**Issue by kasutu** [fzwoch/obs-teleport#89]
I am wondering if this is possible with flutter.

I want to use the phones camera input and stream it to OBS.

considering the same operation when enabling teleport in OBS just by simply turning it on and adding an identifier.

**Comment by fzwoch** [comment]
Not quite sure about the question..

Of course, just write an OBS plugin host - or implement the Teleport protocol in Flutter. But no way without some effort..

**Comment by kasutu** [comment]
Will do, but i would also like to know how teleport works on a higher level since i dont know golang.

Can you provide an explanation of each teleport component on what it does and the protocols ?

Maybe i can scan it in flutter using mDNS

**Comment by fzwoch** [comment]
There is no exact documentation on the format as it may change anytime, but it is not difficult.

Peer discovery is done via multicast broadcast. That means stream sources broadcast in intervals that they exist und clients listen for such messages to know where they are. These message just contain basic JSON data with some information where to connect to for the stream.

The data stream itself is just some small header in front of each data chunk, which is either a JPEG video frame or a couple of PCM audio frames. But for details you have to check the source.

**Comment by kasutu** [comment]
> There is no exact documentation on the format as it may change anytime, but it is not difficult.
> 
> Peer discovery is done via multicast broadcast. That means stream sources broadcast in intervals that they exist und clients listen for such messages to know where they are. These message just contain basic JSON data with some information where to connect to for the stream.
> 
> The data stream itself is just some small header in front of each data chunk, which is either a JPEG video frame or a couple of PCM audio frames. But for details you have to check the source.
> 

That should work, thanks for the info !

**Comment by kasutu** [comment]
Is this the correct service type when searching for broadcasting sources?

```dart
const String serviceType = '_http._tcp';
```

I'm trying to figure out what is the search criteria of the `discoverer.go` so i can discover and announce in flutter.

is there any custom protocol used?

**Comment by fzwoch** [comment]
Absolutely not. :)
It is multicast UDP. It is somewhere in the peerdiscovery dependency. There is a multicast IP address and a port. You have to join that endpoint and send data periodically. The data payload is just a JSON struct with the Peerdiscovery payload that is in `types.go`

**Comment by kasutu** [comment]
Looks like im gonna build peerdiscovery implementation in flutter 😀

Or

Add a webrtc option in obs teleport 👀

**Comment by fzwoch** [comment]
it is really just sending a few dozen bytes to a specific address (and
listen on the same for discovery). it should be fairly simple, although of
course i was happy to see someone did a nice wrapped API for me. I do not
know though what flutter allows..

**Comment by kasutu** [comment]
Got the broadcast from my master OBS.

![Uploading Screenshot_20231220-002151_Multicast Tester.jpg …]()

Will use kotlin instead. 

be right back with the app :)

Thanks alot !

**Comment by kasutu** [comment]
Accidentally deleted the previous comment.

here is my findings:

using [MitchTalmadge/Multicast-Tester](https://github.com/MitchTalmadge/Multicast-Tester) and default `IP` and `PORT`, teleport instances can be discovered.

![image](https://github.com/fzwoch/obs-teleport/assets/64959978/ebb9e58a-32f6-4984-9486-6d474d9bb495)

This leads me to pivot in using java/kotlin.

will be back with the app

thanks a lot @fzwoch !

**Comment by kasutu** [comment]
Got it working on `flutter`

https://github.com/kasutu/obs_teleport_mobile

stay tuned peeps
