### ISSUE TITLE
Teleport not honoring OBS setting for bound IP address?

### ISSUE THREAD

**Issue by LiterangeTechLLC** [fzwoch/obs-teleport#90]
First off, thank you for this excellent tool.

Have just finished setting up a dedicated 10gbs wired subnet specifically for Teleport on an Unreal test box, looking for more stability than what we've been able to achieve with the existing wifi networking on same.

After reconfiguring the networking on both sender and receiver, and binding OBS on the sender to the 10gbs subnet, the sender still presents the wifi IP address for the Teleport connection to the receiver. A quick test of network load on the two NICs indicates that the bits are indeed flowing to the wifi NIC we're trying to move wavy from.

It's not a huge issue, as our workaround is to simply pull some cable and take the wifi down entirely, but this functionality may be beneficial and worth a quick look.

**Comment by fzwoch** [comment]
I don't think it possible for a plugin to read out this setting? Not sure though.

On the other hand, Teleport should broadcast a stream for each interface it has. So on the receiver side it should also show two instances with the same name. It should be distinguishable by the origin IP address in that name whether it is wired or wireless.

That is at least the theory. I'm pretty sure I tested that at some point. It has been a while though and it may be a specific setup only.

**Comment by LiterangeTechLLC** [comment]
Sitting here just thinking the same exact thing and considering what may be doable at the OS level to goad the receiver into seeing the alternate IP address. Not anything groundbreaking, our implementation basically builds a streaming network on the local network to transmit visual data (the desktop) from a machine running a 3d training simulator (running in Unreal) in which the simulator user is physically interacting with the simulator while moving and handling physical objects in the physical environment. The user’s physical actions are captured via a group of cameras managed on a second machine and viewed on the display(s) of that machine along with the visual data from the sim. Any live streaming also is performed by the second machine. Both machines utilize OBS to accomplish the task. 
    Teleport is an extremely simple and elegant tool and the performance is such that the simulator doesn’t suffer any loss of performance even when running Unreal 5. I just need to up the network performance to get the most out of it. Thanks for reaching out!
  

 From: Florian Zwoch ***@***.***>Sent: Wednesday, January 17, 2024 10:03 AMTo: fzwoch/obs-teleport ***@***.***>Cc: LiterangeTechLLC ***@***.***>; Author ***@***.***>Subject: Re: [fzwoch/obs-teleport] Teleport not honoring OBS setting for bound IP address? (Issue #90) 
I don't think it possible for a plugin to read out this setting? Not sure though.
On the other hand, Teleport should broadcast a stream for each interface it has. So on the receiver side it should also show two instances with the same name. It should be distinguishable by the origin IP address in that name whether it is wired or wireless.
That is at least the theory. I'm pretty sure I tested that at some point. It has been a while though and it may be a specific setup only.

**Comment by LiterangeTechLLC** [comment]
Well. I'm an idiot...

Due to some as yet determined reason, Windows designated the subnet on both machines as public network interfaces, greatly restricting the firewall permissions on that interface. Working through that issue on the sender, I forgot to update the firewall settings on the receiver to be adjusted so OBS could see traffic on the subnet.

Once that is done, Teleport on the receiver shows sources on all enabled interfaces on the sender.

My bad, thanks for your attentive reply.
