### ISSUE TITLE
Primary PC still undertaking the stress of encoding

### ISSUE THREAD

**Issue by ProjectKaos** [fzwoch/obs-teleport#91]
Been trying to use Teleport to offload the CPU load onto an ROG Ally using the x264 encoder. I'm having an issue where my main gaming PC still seems to take on the encoding load and I don't know why. My ROG Ally CPU usage is around 50-75%% using it to encode the stream (through teleport) playing Tarkov. However my gaming PC which is broadcasting my OBS stuff through teleport also sees a spike of about 25-35%% CPU usage by just having it open even though its not the one doing the encoding, any idea why?

Perhaps I misunderstand the tool but I was hoping I could offload all the stress of encoding onto a different PC (in this case an ROG Ally) but my main PC still seems to undertake the load. And just to be clear, my main PC does have checked "Enable Teleport", obviously so it can send the signal to my 2nd PC (Rog Ally) and it is NOT checked on the 2nd PC (Rog Ally) as obviously it doesn't need too. It just doesn't seem to offload any of the stress, like I might as well just encode on my main gaming PC as using teleport doesn't alleviate any stress.

Hope that makes sense, thanks!

**Comment by fzwoch** [comment]
There is a bit of CPU overhead when using Teleport. It should be significantly lower than x264 encoding.

You can test the overhead when connecting/disconnecting the receiver. When there is no receiver running Teleport on the the receiving side does nothing.

So if you cannot spot a big difference when connecting/disconnecting to the receiver it is something else causing the load.
