### ISSUE TITLE
[Bug/Issue] teleport will stop transfering to others PC when you active Private Network.

### ISSUE THREAD

**Issue by ingrid-z** [fzwoch/obs-teleport#92]
I think this issue start at 0.7.0

When I stream games, my stream pc preview just stuck as hell, feel like firewall is filtering something
Slashie also mention this issue this on OBS discussion page 12, even OBS allow teleport specific private port it still stuck.
If disable entire private network, the issue solved. But I still think it a bug.

No any strange things log in files.

**Comment by fzwoch** [comment]
Surely nothing network related has changed for a very long time. I cannot tell you what this setting in Windows does. If the firewall does not allow incomming connections it cannot work.

If it does work with no firewall at all.. then it is most likely the firewall.

**Comment by fzwoch** [comment]
Well, if it works but there is stuttering it is most likely a bandwidth constraint.

**Comment by ingrid-z** [comment]
Well even I've down the quality to 50% or under it was still stuttering.  :'<

**Comment by fzwoch** [comment]
You mean mbps? I guess this is via WLAN?

**Comment by ingrid-z** [comment]
I have a 8 ports 2.5Gbps Switch which swap the data between 2 PCs.

Gpon -> (bridge) 1Gbps router -> LAN1 port -> Switch -> Gaming PC and Streaming PC

**Comment by fzwoch** [comment]
I there is nothing in the logs that is Teleport related in any of the machines, then I don't know what it can be.

**Comment by ingrid-z** [comment]
I think it probably Microsoft messed up their firewall, With private firewall on I can't even access my shared folders between two PCs, turn private firewall it will work gain the access to shared folders.


I only found this unusual log in stream machine. probably unrelated.

09:36:22.199: [obs-teleport] connected to: 192.168.50.122:55028
09:44:33.336: adding 21 milliseconds of audio buffering, total audio buffering is now 21 milliseconds (source: Teleport)
09:44:33.336: 
09:58:24.496: [obs-teleport] disconnected from: 192.168.50.122:55028
09:58:36.452: [obs-teleport] connected to: 192.168.50.122:55270
09:59:43.457: adding 42 milliseconds of audio buffering, total audio buffering is now 64 milliseconds (source: Teleport)
09:59:43.457:
