### ISSUE TITLE
Dual PC not showing up in teleport ?

### ISSUE THREAD

**Issue by Lyff-le** [fzwoch/obs-teleport#98]
Hi, i'm sorry to bother you. I'm considering switching to Obs Teleport for twitch livestreams, and currently streaming with a game pc (asus tuf) and a stream pc (macbook pro). 

However, when I follow the steps and hit refresh, I don't see my pc showing up in the list. I tried the other way around and still nothing (endlessly showing "press refresh" despite doing it)

For a bit of background info, I don't have access to an ethernet cable and I use my own wifi for this. Is there anything I'm missing here ?
Thank you so much for your answer !

**Comment by fzwoch** [comment]
Wifi itself is not recommended due to bandwidth.
- check (disable) your firewalls
- check if your router forwards multicast messages between segments you are using (i can't help with that)
