### ISSUE TITLE
peerdiscovery has a bug is effect this plugin

### ISSUE THREAD

**Issue by mohamad-hesari** [fzwoch/obs-teleport#99]
[https://github.com/schollz/peerdiscovery/issues/13](url)

When my pc wakes up from hibernation or sleep, it shows no streams in the dropdown. after disabling the LAN network and re-enabling it, the problem was fixed.
if it is possible we add IP and port by hand, that might be cool

**Comment by fzwoch** [comment]
You can inject a peer with a small script. See https://github.com/fzwoch/obs-teleport/issues/94.

**Comment by fzwoch** [comment]
Have you actually reproduced the issue?

I have put one machine too sleep and woke it up again - the sample app as well as the OBS announce was still working.

**Comment by fzwoch** [comment]
Tried on Windows, putting it to sleep. After sleep discovery worked in both directions, other peers were able to discover the machine as well as other machines were discoverable.

Feels like an OS/driver bug that multicast operations fail after wake from sleep.
